create view PROJEKT_VIEW_MITARBEITER AS
select ARBEITSORT ,ROLLE, count(*) as "Mitarbeiter Anzahl", round(avg(GEHALT)) as Durschnittsgehalt
FROM PROJEKT_MITARBEITER
group by ROLLE, ARBEITSORT;

drop view PROJEKT_VIEW_MITARBEITER;

create view PROJEKT_VIEW_VERKAUF AS
select VERKAUFSORT, sum(GESAMTPREIS) as "Gesamtumsatz", count(*) as "Verkäufe"
FROM PROJEKT_VERKAUF
group by VERKAUFSORT

drop view PROJEKT_VIEW_VERKAUF;

create view PROJEKT_VIEW_LAGER AS
select F.STANDORTNAME, F.STADT, L.PRODUKTID, P.PRODUKTNAME, P.PREIS,  L.ANZAHL
from PROJEKT_LAGERT L
join PROJEKT_PRODUKT P ON L.PRODUKTID = P.PRODUKTID
join PROJEKT_WARENLAGER W ON L.LAGERORT = W.FirmenstandortID
join PROJEKT_FIRMENSTANDORT F ON W.FIRMENSTANDORTID = F.FirmenstandortID;

drop view PROJEKT_VIEW_VERKAUF;

